### ISSUE TITLE
Subsequent pages do not use template

### ISSUE THREAD

**Issue by fritzmg** [inspiredminds/contao-isotope-pdf-templates#1]
Currently, only the first pages uses the template. If the HTML is wrapped onto another page, the template isn't used at the subsequent pages.

**Comment by fritzmg** [comment]
Fixed in version 2.0.0 by using mPDF

**Comment by hangarsieben** [comment]
Is it technically feasible to use the second page of a PDF template file on subsequent pages (if the template in use does have two pages)?

**Comment by fritzmg** [comment]
That should already be the case.
