### ISSUE TITLE
Do not depend on contao/tcpdf-bundle

### ISSUE THREAD

**Issue by fritzmg** [inspiredminds/contao-isotope-pdf-templates#2]
The usage of certain constants makes this extension dependent on contao/tcpdf-bundle, which technically it should not. This results in errors like

```
Unknown page format PDF_PAGE_FORMAT
```

**Comment by hangarsieben** [comment]
Is there any rough timeframe for when tcpdf-dependency will be removed? I am currently testing contao-isotope-pdf-templates with Contao 4.9 and am receiving the same error

`Unknown page format PDF_PAGE_FORMAT`

**Comment by fritzmg** [comment]
As a quick fix you can just add the missing constants into your `contao/config/config.php`. You can take the default values from here for example: https://github.com/contao/tcpdf-bundle/blob/f5c06a420479452153b0e130271a0b63c5b97a39/src/Resources/contao/config/tcpdf.php#L13-L48

**Comment by hangarsieben** [comment]
Thank you for the speedy solution - I will try that!

**Comment by fritzmg** [comment]
Just for reference, the following constants are needed: https://github.com/inspiredminds/contao-isotope-pdf-templates/blob/854a6589fd2bd83bafc1a4fbd0bf97f904ffd2eb/src/Isotope/Model/Document/Template.php#L63-L75

**Comment by fritzmg** [comment]
@colonelpanick could you please test the current `master` branch, without having defined your own constants? (Except the ones you need.)

**Comment by fritzmg** [comment]
Fix released with `2.1.1`.
