### ISSUE TITLE
PDFs only created in order state "Completed"

### ISSUE THREAD

**Issue by DrAColian** [inspiredminds/contao-isotope-pdf-templates#5]
Hello,

as the titel states, I can only create user defined PDF documents for Istotope orders if they are in "completed" state. Any other order state (like "open" or "in progress") will create a PDF with the default template, though the document type itself has the correct template selected.

Contao 4.13.8
Isotope 2.8.7
PDF Templates 2.2.1

[edit: changed to english]

**Comment by fritzmg** [comment]
And this does not happen anymore if you uninstall the extension?

**Comment by DrAColian** [comment]
Correct. I can print all documents as PDF, with the correct templates, but due to the missing mpdf support, the formatting is way of.

**Comment by fritzmg** [comment]
I don't see how this could be related to the extension - or order statuses for that matter. The [`Template`](https://github.com/inspiredminds/contao-isotope-pdf-templates/blob/master/src/Isotope/Model/Document/Template.php) Isotope Document type simply extends from `Isotope\Model\Document\Standard` - and uses its `generateTemplate` method. In there a new template is created with the chosen template name. At no point does Isotope (or this extension) query order statuses before hand - or uses order statuses to determine the template name.

**Comment by DrAColian** [comment]
I thought so too, from my short glimpse into the source code - question is: any chance for me to debug and find out, what stops the "real" template to be used?

Just checked: when I change the status from "completed" to "open" the same issue happens. So it is defintely linked to the status, but I don't know why and how.

**Comment by fritzmg** [comment]
You could insert a `dump($this->documentTpl); exit;` [here](https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/Model/Document/Standard.php#L171) and then compare if this value is truly different depending on the status.

**Comment by DrAColian** [comment]
As you might have guessed: it's the same. Means, the "exchange" must happen afterwards. Or maybe the right template name is given, its content might be different - namely the one of the default template. (Don't ask me how. :D)

**Comment by fritzmg** [comment]
I think you will need to debug this in more detail in your Contao instance.

**Comment by DrAColian** [comment]
Ok. I tried to find out more, but as I'm not really deep into Contao or Isotope source, I need some guidance.

So, the documentTpl is correct. But when '$strBuffer' is created [here](https://github.com/isotope/core/blob/2.8/system/modules/isotope/library/Isotope/Model/Document/Standard.php#L205), it already contains the wrong data. So right now, I'm trying to find the "parse" function for "Template".

But even then, I cannot be sure that another module isn't interfering with this parse function.

**Comment by fritzmg** [comment]
Make a search for `generateDocumentTemplate` in your whole Contao instance. Does anything besides  `vendor\isotope\isotope-core\system\modules\isotope\config\config.php` or `vendor\isotope\isotope-core\system\modules\isotope\library\Isotope\Model\Document\Standard.php` come up?

**Comment by DrAColian** [comment]
No. Just those two.

If I dump `$strBuffer` right after [here](https://github.com/contao/contao/blob/4.13/core-bundle/src/Resources/contao/classes/FrontendTemplate.php#L43) it's already wrong. But `$this->strTemplate` shows the correct template name. Now, I don't know, how to find out what `parent` is, and where it comes from.

**Comment by fritzmg** [comment]
Closing as this is unlikely related to this extension.
